<?php

namespace Database\Seeders;

use App\Models\Car;
use Illuminate\Database\Seeder;

class CarSeeder extends Seeder
{
    public function run(): void
    {
        $cars = [
            [
                'key' => 'model_3',
                'name' => 'Tesla Model 3',
                'desc' => 'Electric Sedan · 358mi range · 510hp',
                'fee' => '$299',
                'image' => 'img/tesla-model-3.jpg',
                'category' => 'Performance Sedan',
                'badge' => 'Most Popular',
                'power' => '510 hp Dual Motor',
                'range' => '358 mi Range',
                'delivery' => '7–10 Business Days',
                'gradient' => 'from-gray-900 to-gray-800',
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'key' => 'model_y',
                'name' => 'Tesla Model Y',
                'desc' => 'Electric SUV · 330mi range · 384hp',
                'fee' => '$349',
                'image' => 'img/tesla-model-y.jpg',
                'category' => 'Premium SUV',
                'badge' => '⚡ Express Delivery',
                'power' => '384 hp Electric',
                'range' => '330 mi Range',
                'delivery' => '5–7 Business Days',
                'gradient' => 'from-sky-800 to-sky-900',
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'key' => 'model_s',
                'name' => 'Tesla Model S',
                'desc' => 'Luxury Sedan · 405mi range · 670hp',
                'fee' => '$399',
                'image' => 'img/tesla-model-s.jpg',
                'category' => 'Luxury Flagship',
                'badge' => '👑 Premium',
                'power' => '670 hp Tri Motor',
                'range' => '405 mi Range',
                'delivery' => '3–5 Business Days',
                'gradient' => 'from-red-800 to-red-900',
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'key' => 'model_x',
                'name' => 'Tesla Model X',
                'desc' => 'Luxury SUV · 348mi range · 670hp',
                'fee' => '$249',
                'image' => 'img/tesla-model-x.jpg',
                'category' => 'Luxury SUV',
                'badge' => '💚 Best Value',
                'power' => '670 hp Tri Motor',
                'range' => '348 mi Range',
                'delivery' => '10–14 Business Days',
                'gradient' => 'from-emerald-700 to-emerald-900',
                'sort_order' => 4,
                'is_active' => true,
            ],
            [
                'key' => 'cybertruck',
                'name' => 'Tesla Cybertruck',
                'desc' => 'Electric Truck · 340mi range · 845hp',
                'fee' => '$379',
                'image' => 'img/tesla-cybertruck.jpg',
                'category' => 'Electric Truck',
                'badge' => '🎉 New Arrival',
                'power' => '845 hp Tri Motor',
                'range' => '340 mi Range',
                'delivery' => '5–8 Business Days',
                'gradient' => 'from-violet-800 to-violet-900',
                'sort_order' => 5,
                'is_active' => true,
            ],
            [
                'key' => 'roadster',
                'name' => 'Tesla Roadster',
                'desc' => 'Ultra Performance · 620mi range · 1000+hp',
                'fee' => '$499',
                'image' => 'img/tesla-roadster.jpg',
                'category' => 'Ultra Performance',
                'badge' => '💎 Ultra Luxury',
                'power' => '1000+ hp Electric',
                'range' => '620 mi Range',
                'delivery' => '3–5 Business Days',
                'gradient' => 'from-slate-800 to-slate-900',
                'sort_order' => 6,
                'is_active' => true,
            ],
            [
                'key' => 'model_3_sr',
                'name' => 'Tesla Model 3 SR',
                'desc' => 'Standard Range · 272mi range · 283hp',
                'fee' => '$199',
                'image' => 'img/tesla-model-3.jpg',
                'category' => 'Standard Range',
                'badge' => '🏙️ City Special',
                'power' => '283 hp RWD',
                'range' => '272 mi Range',
                'delivery' => '10–14 Business Days',
                'gradient' => 'from-cyan-700 to-cyan-900',
                'sort_order' => 7,
                'is_active' => true,
            ],
            [
                'key' => 'model_y_lr',
                'name' => 'Tesla Model Y LR',
                'desc' => 'Long Range SUV · 330mi range · 384hp',
                'fee' => '$329',
                'image' => 'img/tesla-model-y.jpg',
                'category' => 'Long Range SUV',
                'badge' => '👨‍👩‍👧 Family Pick',
                'power' => '384 hp AWD',
                'range' => '330 mi Range',
                'delivery' => '7–10 Business Days',
                'gradient' => 'from-indigo-800 to-indigo-900',
                'sort_order' => 8,
                'is_active' => true,
            ],
            [
                'key' => 'model_s_plaid',
                'name' => 'Tesla Model S Plaid',
                'desc' => 'Performance Sedan · 396mi range · 1020hp',
                'fee' => '$359',
                'image' => 'img/tesla-model-s.jpg',
                'category' => 'Performance Sedan',
                'badge' => '⭐ Top Rated',
                'power' => '1020 hp Tri Motor',
                'range' => '396 mi Range',
                'delivery' => '5–7 Business Days',
                'gradient' => 'from-zinc-700 to-zinc-900',
                'sort_order' => 9,
                'is_active' => true,
            ],
        ];

        foreach ($cars as $car) {
            Car::updateOrCreate(['key' => $car['key']], $car);
        }
    }
}
